// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("ValidatedTypes.DesignTime")>]
[<assembly: AssemblyProductAttribute("ValidatedTypes")>]
[<assembly: AssemblyDescriptionAttribute("This library is for the .NET platform implementing ValidatedTypes.")>]
[<assembly: AssemblyVersionAttribute("1.0.0")>]
[<assembly: AssemblyFileVersionAttribute("1.0.0")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "ValidatedTypes.DesignTime"
    let [<Literal>] AssemblyProduct = "ValidatedTypes"
    let [<Literal>] AssemblyDescription = "This library is for the .NET platform implementing ValidatedTypes."
    let [<Literal>] AssemblyVersion = "1.0.0"
    let [<Literal>] AssemblyFileVersion = "1.0.0"
